# Generated by Django 5.2.3 on 2025-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
