# Generated by Django 5.2.3 on 2025-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0002_vpnuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='full_name',
            field=models.CharField(
                blank=True, help_text='Человекочитаемое имя пользователя', max_length=255, null=True,
            ),
        ),
        migrations.AlterField(
            model_name='vpnuser',
            name='telegram_id',
            field=models.BigIntegerField(help_text='Числовой Telegram user ID', unique=True),
        ),
        migrations.AlterField(
            model_name='vpnuser',
            name='username',
            field=models.CharField(help_text='Telegram-ник с @, если установлен', max_length=255),
        ),
    ]
