# Generated by Django 5.2.3 on 2025-07-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0003_vpnuser_full_name_alter_vpnuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnuser',
            name='full_name',
            field=models.CharField(help_text='Человекочитаемое имя пользователя', max_length=255),
        ),
        migrations.AlterField(
            model_name='vpnuser',
            name='username',
            field=models.CharField(help_text='Telegram-ник, который начинается с @ (указывать без @)', max_length=255),
        ),
    ]
