# Generated by Django 5.2.3 on 2025-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0004_alter_vpnuser_full_name_alter_vpnuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnuser',
            name='username',
            field=models.CharField(help_text='Telegram-ник с @', max_length=255),
        ),
    ]
