# Generated by Django 5.2.3 on 2025-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0005_alter_vpnuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnuser',
            name='username',
            field=models.CharField(blank=True, help_text='Telegram-ник с @', max_length=255, null=True),
        ),
    ]
