# Generated by Django 5.2.3 on 2025-07-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0006_alter_vpnuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='amneziawgconfig',
            name='private_key',
            field=models.CharField(
                blank=True, help_text='Приватный ключ AmneziaWG для восстановления конфигурации', max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name='vpnuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Для админа нет ограничения на количество конфигов'),
        ),
    ]
