# Generated by Django 5.2.3 on 2025-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0007_amneziawgconfig_private_key_alter_vpnuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='amneziawgconfig',
            name='allowed_ip',
            field=models.CharField(blank=True, help_text='IP-адрес, разрешенный для этого клиента', max_length=255),
        ),
        migrations.AlterField(
            model_name='amneziawgconfig',
            name='private_key',
            field=models.CharField(
                blank=True,
                help_text='Приватный ключ AmneziaWG, необходимый для восстановления конфигурации',
                max_length=255,
            ),
        ),
    ]
