# Generated by Django 5.2.3 on 2025-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_amneziawgconfig_allowed_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amneziawgconfig',
            name='client_id',
            field=models.CharField(blank=True, help_text='Добавляется автоматически', max_length=255),
        ),
        migrations.AlterField(
            model_name='amneziawgconfig',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Дата окончания действия конфигурации'),
        ),
        migrations.AlterField(
            model_name='vlessconfig',
            name='client_id',
            field=models.UUIDField(blank=True, help_text='Добавляется автоматически'),
        ),
        migrations.AlterField(
            model_name='vlessconfig',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Дата окончания действия конфигурации'),
        ),
        migrations.AlterField(
            model_name='vpnuser',
            name='available_configs_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
