# Generated by Django 5.2.3 on 2025-09-11 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_alter_amneziawgconfig_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, help_text='Комментарий администратора')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='vpn.vpnuser')),
            ],
        ),
    ]
