# Generated by Django 5.2.3 on 2025-09-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='amneziawgconfig',
            name='ip_address',
            field=models.GenericIPAddressField(default='45.12.142.121', help_text='IP-адрес сервера, для которого создан конфиг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlessconfig',
            name='ip_address',
            field=models.GenericIPAddressField(default='45.12.142.121', help_text='IP-адрес сервера, для которого создан конфиг'),
            preserve_default=False,
        ),
    ]
