# Generated by Django 5.2.3 on 2025-09-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_amneziawgconfig_ip_address_vlessconfig_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amneziawgconfig',
            old_name='ip_address',
            new_name='server_ip_address',
        ),
        migrations.RenameField(
            model_name='vlessconfig',
            old_name='ip_address',
            new_name='server_ip_address',
        ),
    ]
