# Generated by Django 5.2.3 on 2025-09-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0012_rename_ip_address_amneziawgconfig_server_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Удобное имя сервера', max_length=100, unique=True)),
                ('host', models.GenericIPAddressField(help_text='IP-адрес сервера')),
                ('ssh_port', models.IntegerField(default=22)),
                ('ssh_user', models.CharField(default='root', max_length=50)),
                ('max_configs', models.IntegerField(default=100, help_text='Максимальное число конфигов')),
                ('issued_configs', models.IntegerField(default=0, help_text='Сколько конфигов выдано на данный момент')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VPN сервер',
                'verbose_name_plural': 'VPN сервера',
            },
        ),
        migrations.RemoveField(
            model_name='amneziawgconfig',
            name='server_ip_address',
        ),
        migrations.RemoveField(
            model_name='vlessconfig',
            name='server_ip_address',
        ),
        migrations.CreateModel(
            name='ServerProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('amneziawg', 'AmneziaWG')], help_text='Какой протокол поддерживает сервер', max_length=50)),
                ('config_path', models.CharField(help_text='Путь к конфигурационным файлам внутри контейнера', max_length=255)),
                ('container_name', models.CharField(help_text='Имя docker-контейнера', max_length=100)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='vpn.vpnserver')),
            ],
        ),
    ]
