# Generated by Django 5.2.3 on 2025-09-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0013_vpnserver_remove_amneziawgconfig_server_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amneziawgconfig',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vpn.vpnserver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlessconfig',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vpn.vpnserver'),
            preserve_default=False,
        ),
    ]
