# Generated by Django 5.2.3 on 2025-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0014_amneziawgconfig_server_vlessconfig_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprotocol',
            name='config_filename',
            field=models.CharField(default='config.json', help_text='Имя конфигурационного файла', max_length=50),
        ),
        migrations.AddField(
            model_name='serverprotocol',
            name='is_clients_table_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverprotocol',
            name='public_key',
            field=models.CharField(help_text='Публичный ключ сервера для конфигураций клиентов', max_length=255),
        ),
        migrations.AlterField(
            model_name='serverprotocol',
            name='config_path',
            field=models.CharField(
                default='/etc/xray/', help_text='Путь к конфигурационным файлам внутри контейнера', max_length=255
            ),
        ),
        migrations.AlterField(
            model_name='serverprotocol',
            name='container_name',
            field=models.CharField(default='xray-server', help_text='Имя docker-контейнера', max_length=100),
        ),
        migrations.AlterField(
            model_name='serverprotocol',
            name='protocol',
            field=models.CharField(
                choices=[('vless', 'VLESS'), ('amneziawg', 'AmneziaWG')],
                default='vless',
                help_text='Какой протокол поддерживает сервер',
                max_length=50,
            ),
        ),
    ]
