# Generated by Django 5.2.3 on 2025-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0015_serverprotocol_config_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprotocol',
            name='wg_preshared_key',
            field=models.CharField(blank=True, help_text='(только для AmneziaWG) Общий ключ WireGuard', max_length=255),
        ),
    ]
