# Generated by Django 5.2.3 on 2025-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0016_serverprotocol_wg_preshared_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnserver',
            name='issued_configs',
        ),
        migrations.AddField(
            model_name='serverprotocol',
            name='volumes_supported',
            field=models.BooleanField(default=False, help_text='Поддерживает ли сервер монтирование volumes (для AmneziaWG)'),
        ),
        migrations.AlterField(
            model_name='serverprotocol',
            name='config_path',
            field=models.CharField(default='/etc/xray/', help_text='Путь к конфигурационным файлам', max_length=255),
        ),
    ]
