# Generated by Django 5.2.3 on 2025-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0017_remove_vpnserver_issued_configs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverprotocol',
            name='volumes_supported',
            field=models.BooleanField(default=True, help_text='Поддерживает ли сервер монтирование volumes (для AmneziaWG)'),
        ),
    ]
