# Generated by Django 5.2.3 on 2025-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0018_alter_serverprotocol_volumes_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnserver',
            name='location',
            field=models.CharField(default='Netherlands', help_text='Географическое расположение сервера', max_length=50),
        ),
    ]
