# Generated by Django 5.2.3 on 2025-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vpn', '0019_vpnserver_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlessconfig',
            name='config_email',
            field=models.CharField(
                default='default_email',
                help_text='Email для конфига (используется для сбора статистики, добавляется автоматически)',
            ),
            preserve_default=False,
        ),
    ]
